#myapp: graphics.c
#	gcc $(pkg-config --cflags gtk+-3.0) graphics.c -o p1  $(pkg-config --libs gtk+-3.0)



# change application name here (executable output name)
TARGET=sudoku

# compiler
CC=gcc
# debug
DEBUG=-g
# optimisation
OPT=-O0
# warnings
WARN=-Wall

PTHREAD=-pthread

CCFLAGS=$(DEBUG) $(OPT) $(WARN) $(PTHREAD) -pipe

GTKLIB=`pkg-config --libs gtk+-3.0`
GTKFLAGS=`pkg-config --cflags gtk+-3.0`

# linker
LD=gcc
LDFLAGS=$(PTHREAD) $(GTKLIB) -export-dynamic
COBJS=main.c window.c file.c
OBJS=main.o

$(TARGET):$(OBJS)
	$(LD) $(GTKFLAGS) $(COBJS) $(GTKLIB) -o $(TARGET)

# window.o: window.c
# 	$(CC) -c $(CCFLAGS) window.c window.o $(GTKLIB) -o window.o

# $(OBJS):$(COBJ)
# 	$(CC) -c $(CCFLAGS) $(COBJ) $(GTKLIB) -o $(OBJS)


clean:
	rm -f *.o $(TARGET)

